### ISSUE TITLE
Sprint 1 Roadmap

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-tip/wp-rules#1]
This is the first sprint so most of work will be on the architecture and main design so it's very important to make is solid as much as we can.

## Product Overview:

We will start this project to help non developers to be able to create business rules without any programming knowledge.

### Some examples:-

1. You want to create a rule to **Send an email** to one of admins when an **editor publish a new post** with specific contents.
2. You want to create a rule to **Redirect Editors or one editor to a specific page** when **Logged in**.
3. You want to create a rule to **Change user meta field** when **user registers**.
4. You want to create a rule to **Send an email** (report) to admin when **the date is first day of every month**.

And too many options.

### Main Components:

![wp-rules](https://user-images.githubusercontent.com/15707971/100169234-9fd97700-2ecb-11eb-8d23-b847f55c0ef8.jpg)

**Rules:** Those are the business rules that will contain rule name, trigger, some conditions and actions inside it, like container only.

**Trigger:** This is the main entry for any active rule so this needs to be active to fire the process of checking conditions and perform actions, and basically this will be Wordpress Hooks ( actions ). 
**WE WILL START WITH ONE TRIGGER PER RULE FOR NOW.**

**Conditions:** Those are the conditions needs to be all true to perform actions.

**Actions:** Those are the actions that will be executed like sending email, show admin notice, ...etc.

## Sprint 1 Planning

I will state below the features we need to have this sprint and some details about this sprint:-

- [x] **[Architecture]** Folder structure: we need to put a plan for folder structure as we will depend on composer autoloader so we need to know how will we organize our code and assets into the plugin.

- [x] **[Architecture]** Main files structure: So we will use composer autoloader, will set some constants and make the plugin work (even with empty interface)

- [x] **[Architecture]** Database structure: So we will take the decision to use our own DB tables or map wordpress DB to meet our needs.

- [x] **[Architecture]** Tests structure: make tests structure (unit - integration - fixtures) and adjust the bootstrap files to make tests work (even without any tests yet).
