### ISSUE TITLE
Sprint 2 Roadmap

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-tip/wp-rules#14]
# Sprint 2

After making good analysis and planning at Sprint 1, we need to build the remaining main functionality for the admin part on this sprint 2 as follows:-

## Trigger

- [x] Make trigger structure, the contract (interface) that should each trigger implement.

- [x] Save trigger custom field.

## Condition

- [x] Make condition default structure.

- [x] Add the JS script to add new condition.

- [x] Add the ajax request to grab condition option fields.

- [x] Save All conditions into custom fields based on decision had been taken here #4 

## Action

- [x] Make action default structure.

- [x] Add the JS script to add new action.

- [x] Add the ajax request to grab action option fields.

- [x] Save All actions into custom fields based on decision had been taken here #4 

## Tests

- [ ] Add unit tests for the full admin part.

- [ ] Add Integration tests for the full admin part.
