### ISSUE TITLE
Update plugin meta

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-tip/wp-rules#76]
- [x] Change plugin author to be `wp-tip`
- [x] Change plugin name to be `Business Rules`
- [x] Change plugin URI to be `https://github.com/wp-tip/wp-rules`
- [x] Change author URI to be `https://github.com/wp-tip`
